# This file was generated by GoReleaser. DO NOT EDIT.
class Msconsole < Formula
  desc "A suite of tools to make your life easier!"
  homepage "https://github.com/tempor1s/msconsole"
  version "1.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tempor1s/msconsole/releases/download/v1.1.4/msconsole_1.1.4_macOS-64bit.tar.gz"
    sha256 "2ad8617b8de2e125420116f879f8df3995d8a3f4eb4cc1c20e13c48f5d553cb3"
  elsif OS.linux?
  end

  def install
    bin.install "ms"
  end
end
