# This file was generated by GoReleaser. DO NOT EDIT.
class Msconsole < Formula
  desc "A suite of tools to make your life easier!"
  homepage "https://github.com/tempor1s/msconsole"
  version "1.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tempor1s/msconsole/releases/download/v1.1.5/msconsole_1.1.5_macOS-64bit.tar.gz"
    sha256 "998bf8a61d0a75bbce1ed839587a582d3c4d9dcbb5543df037aafa10e99c195a"
  elsif OS.linux?
  end

  def install
    bin.install "ms"
  end
end
