# This file was generated by GoReleaser. DO NOT EDIT.
class MsconsoleGo < Formula
  desc "A suite of tools to make your life easier!"
  homepage "https://github.com/tempor1s/msconsole-go"
  version "1.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tempor1s/msconsole-go/releases/download/v1.0.4/msconsole-go_1.0.4_macOS-64bit.tar.gz"
    sha256 "76c51a5c340f4db6b404e2470d267c3d53e62faff584d7c62e25eb4f21ea8283"
  elsif OS.linux?
  end

  def install
    bin.install "msc"
  end
end
